export enum PermissionsList {
  USERS_READ = 'USERS_READ',
  USERS_CREATE = 'USERS_CREATE',
  USERS_DELETE = 'USERS_DELETE',
  USERS_UPDATE = 'USERS_UPDATE',

  ROLES_READ = 'ROLES_READ',
  ROLES_CREATE = 'ROLES_CREATE',
  ROLES_DELETE = 'ROLES_DELETE',
  ROLES_UPDATE = 'ROLES_UPDATE',

  PERMISSIONS_READ = 'PERMISSIONS_READ',
  PERMISSIONS_CREATE = 'PERMISSIONS_CREATE',
  PERMISSIONS_DELETE = 'PERMISSIONS_DELETE',
  PERMISSIONS_UPDATE = 'PERMISSIONS_UPDATE',
}
