allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  '@scarf/scarf': true
  bcrypt: true
  prisma: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@hono/node-server@1.19.13'
  - hono@4.12.21
  - form-data@4.0.6
  - '@babel/core@7.29.1'
  - hono@4.12.25
  - multer@2.2.0
  - js-yaml@3.15.0
  - js-yaml@4.1.2
overrides:
  '@hono/node-server@<1.19.13': ^1.19.13
